apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-starter
  title: Python Service com CI/CD
  description: Cria um serviço Python simples com GitHub Actions configurado.
spec:
  owner: guests
  type: service

  # O formulário que o usuário vai preencher na tela
  parameters:
    - title: Informações do Serviço
      required:
        - name
        - owner
      properties:
        name:
          title: Nome do Serviço
          type: string
          description: Nome único do projeto
          ui:autofocus: true
        owner:
          title: Dono (Owner)
          type: string
          description: Quem é dono desse componente
          default: guests
    
    - title: Localização
      required:
        - repoOwner
      properties:
        repoOwner:
          title: Organização/Usuário GitHub
          type: string
          description: Onde o repo será criado

  # O passo a passo que o Backstage vai executar
  steps:
    - id: fetch-base
      name: Baixando esqueleto do código
      action: fetch:template
      input:
        url: ./content # Pega o conteúdo da pasta 'content'
        values:
          name: ${{ parameters.name }}
          repoOwner: ${{ parameters.repoOwner }}

    - id: publish
      name: Publicando no GitHub
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: 'github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.name }}'
        defaultBranch: main

    - id: register
      name: Registrando no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'