apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-starter
  title: Python Service CI/CD
  description: Scaffold a Python service with CI/CD using GitHub Actions and Docker.
  tags:
    - python
    - ci/cd
    - github-actions
    - docker
spec:
  owner: guests
  type: service

    parameters:
        - title: Informacoes do servico
        required:
            - name
            - owner
        properties:
            name:
            type: string
            title: Service Name
            description: The name of the Python service.
            ui:autofocus: true
            owner:
            type: string
            title: Service Owner
            description: The owner of the service.
            default: guests
        - title: Localizacao do repositorio
        required:
            - repoOwner
        properties:
            repoOwner:
            type: string
            title: Repository Owner
            description: The owner of the GitHub repository.
    steps:
      - id: fetch-base
        name: Baixando template base
        action: fetch:template
        input:
          url: ./content
          values:
            name: ${{ parameters.name }}

      - id: publish
        name: Publish to GitHub
        action: publish:github
        input:
          alloedHosts:
            - github.com
          repoUrl:'github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.name }}'
          defaultBranch: main
          description: 'A Python service scaffolded with Backstage.'
      - id: register
        name: Register in Software Catalog
        action: catalog:register
        input:
          repoContentPath: '/catalog-info.yaml'
          repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}